### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by geomtech** [falon/CSI-telegraf-plugins#1]
Hello,

I compiled your plugin and I had this error when I'm trying to run it with the following command: 
`/bin/telegraf-389ds -config /etc/telegraf/plugins/389ds/389ds.conf`

```
[[inputs.ds389]]
  host = "localhost"
  port = 389
  tls = ""
  insecure_skip_verify = true
  #tls_ca = "/etc/ssl/certs.pem"

  bind_dn = "XXXXXXXXXXXXXXXXXXX"
  bind_password = "XXXXXXXXXXXXXXXXX"

  dbtomonitor = ["userRoot"]
  alldbmonitor = false
  status = true
```

Here's the error I'm having : 
```
2022/04/21 17:37:31 E! Error in plugin: LDAP Result Code 49 "Invalid Credentials":
failed to gather metrics: LDAP Result Code 49 "Invalid Credentials":
```
I don't understand because my credentials are working if I test them with Apache Directory Studio for example, I also tried to run it with the Directory Manager account.
Can you help me please ? Thanks

**Comment by falon** [comment]
Hello Alexy,

  you must use
```
bindDn = "XXX"
bindPassword = "XXX"
```

I fixed this in the default conf, but not in the README. Thank you!
